version: '3'
services:
  webdav:
    container_name: webdav
    image: derkades/webdav   
    volumes:
      - /mnt/store/webdav:/data
    networks:
      - global

networks:
  global:
    external:
      name: global
