version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /mnt/store/npm/data:/data
      - /mnt/store/npm/letsencrypt:/etc/letsencrypt
    networks:
      - global

networks:
  second:
    external:
      name: bridge