version: '3'
services:
  webdav:
    image: derkades/webdav:latest
    restart: always
    volumes:
      - /mnt/store/webdav:/var/lib/dav
    networks:
      - global

networks:
  global:
    external:
      name: global
