version: '3'

services:
  bitwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    volumes:
      - /mnt/store/bitwarden:/data
    networks:
      - global
      - bridge

networks:
  default:
    external:
      name: global
  second:
    external:
      name: bridge